// 100 realistic user profiles for network visualization

export interface BaseProfile {
  id: string
  name: string
  role: string
  company: string
  status: "unexplored" | "simulated" | "matched" | "connected"
  compatibility?: number
  skills: string[]
  avatar?: string
}

export const PROFILES: BaseProfile[] = [
  // Matched profiles (high compatibility)
  { id: "1", name: "Sarah Chen", role: "CTO", company: "Fintech Startup", status: "matched", compatibility: 94, skills: ["Distributed Systems", "Go", "Kubernetes"] },
  { id: "2", name: "Marcus Reed", role: "Eng Lead", company: "Series B Company", status: "matched", compatibility: 87, skills: ["React", "TypeScript", "Node.js"] },
  { id: "3", name: "Julia Park", role: "PM", company: "AI Company", status: "connected", compatibility: 91, skills: ["Product Strategy", "AI/ML", "Growth"] },
  { id: "4", name: "Chris Patel", role: "Angel Investor", company: "Independent", status: "matched", compatibility: 89, skills: ["Investing", "Mentorship", "B2B"] },
  { id: "5", name: "Lisa Wang", role: "Co-founder", company: "Web3 Startup", status: "matched", compatibility: 85, skills: ["Blockchain", "Solidity", "DeFi"] },
  { id: "6", name: "Priya Sharma", role: "CRO", company: "SaaS Unicorn", status: "matched", compatibility: 82, skills: ["Revenue Ops", "Enterprise Sales", "GTM"] },
  { id: "7", name: "Michael Zhang", role: "VP Engineering", company: "Scale-up", status: "matched", compatibility: 88, skills: ["Architecture", "Leadership", "Scalability"] },
  { id: "8", name: "Emily Rodriguez", role: "Head of Product", company: "Series A", status: "connected", compatibility: 90, skills: ["Product Management", "User Research", "Analytics"] },
  { id: "9", name: "James Kim", role: "Tech Lead", company: "Enterprise", status: "matched", compatibility: 86, skills: ["Java", "Microservices", "Cloud"] },
  { id: "10", name: "Olivia Martinez", role: "Design Director", company: "Design Studio", status: "connected", compatibility: 83, skills: ["UX Design", "Design Systems", "Research"] },
  { id: "11", name: "Daniel Thompson", role: "Founder", company: "B2B SaaS", status: "matched", compatibility: 84, skills: ["Strategy", "Fundraising", "GTM"] },
  { id: "12", name: "Sophia Anderson", role: "Data Science Lead", company: "AI Lab", status: "matched", compatibility: 87, skills: ["ML", "Python", "Statistics"] },
  { id: "13", name: "Ryan O'Connor", role: "Engineering Manager", company: "Tech Corp", status: "connected", compatibility: 85, skills: ["Team Building", "Agile", "Mentorship"] },
  { id: "14", name: "Ava Lee", role: "Product Manager", company: "Consumer App", status: "matched", compatibility: 88, skills: ["Product Strategy", "Growth", "Analytics"] },
  { id: "15", name: "Noah Brown", role: "Staff Engineer", company: "FAANG", status: "matched", compatibility: 92, skills: ["Systems Design", "Performance", "Infrastructure"] },
  { id: "16", name: "Isabella Garcia", role: "VP Marketing", company: "Series B", status: "connected", compatibility: 81, skills: ["Brand Strategy", "Growth Marketing", "Content"] },
  { id: "17", name: "Liam Wilson", role: "CTO", company: "Startup", status: "matched", compatibility: 89, skills: ["Full Stack", "DevOps", "Leadership"] },
  { id: "18", name: "Mia Johnson", role: "Head of Engineering", company: "Scale-up", status: "matched", compatibility: 86, skills: ["Backend", "Scalability", "Team Leadership"] },
  { id: "19", name: "Ethan Davis", role: "Co-founder", company: "Fintech", status: "connected", compatibility: 90, skills: ["Product", "Strategy", "Fundraising"] },
  { id: "20", name: "Charlotte White", role: "Engineering Lead", company: "AI Startup", status: "matched", compatibility: 87, skills: ["ML Engineering", "Python", "TensorFlow"] },
  { id: "21", name: "Alexander Harris", role: "VP Product", company: "Enterprise SaaS", status: "matched", compatibility: 85, skills: ["Product Strategy", "Enterprise", "GTM"] },
  { id: "22", name: "Amelia Clark", role: "Design Lead", company: "Consumer Tech", status: "connected", compatibility: 84, skills: ["UI/UX", "Design Systems", "Prototyping"] },
  { id: "23", name: "Benjamin Lewis", role: "Principal Engineer", company: "Tech Company", status: "matched", compatibility: 91, skills: ["Architecture", "Distributed Systems", "Performance"] },
  { id: "24", name: "Harper Walker", role: "Head of Growth", company: "Series A", status: "connected", compatibility: 82, skills: ["Growth Marketing", "Analytics", "Experimentation"] },
  { id: "25", name: "Mason Hall", role: "Founder", company: "Web3", status: "matched", compatibility: 88, skills: ["Blockchain", "Crypto", "DeFi"] },

  // Simulated profiles (in process)
  { id: "26", name: "David Kim", role: "Founder", company: "B2B SaaS", status: "simulated", skills: ["Sales", "Fundraising", "Strategy"] },
  { id: "27", name: "Alex Morgan", role: "VP Engineering", company: "Enterprise Co", status: "simulated", skills: ["Java", "Architecture", "Leadership"] },
  { id: "28", name: "Emma Wilson", role: "Design Lead", company: "Design Agency", status: "simulated", skills: ["UX", "Figma", "Design Systems"] },
  { id: "29", name: "Tom Brown", role: "ML Engineer", company: "AI Lab", status: "simulated", skills: ["PyTorch", "NLP", "Computer Vision"] },
  { id: "30", name: "Kevin O'Brien", role: "Architect", company: "Consulting", status: "simulated", skills: ["Cloud", "Microservices", "Security"] },
  { id: "31", name: "Jennifer Taylor", role: "Product Manager", company: "Tech Startup", status: "simulated", skills: ["Product", "Analytics", "User Research"] },
  { id: "32", name: "Robert Singh", role: "Engineering Manager", company: "Scale-up", status: "simulated", skills: ["Team Leadership", "Agile", "Hiring"] },
  { id: "33", name: "Jessica Moore", role: "Head of Design", company: "Consumer App", status: "simulated", skills: ["Design Strategy", "Research", "Prototyping"] },
  { id: "34", name: "William Jackson", role: "Tech Lead", company: "Enterprise", status: "simulated", skills: ["Backend", "Scalability", "Architecture"] },
  { id: "35", name: "Ashley Wright", role: "VP Engineering", company: "Series B", status: "simulated", skills: ["Engineering Leadership", "Process", "Culture"] },
  { id: "36", name: "Matthew Green", role: "Founder", company: "SaaS", status: "simulated", skills: ["Product", "Sales", "Strategy"] },
  { id: "37", name: "Samantha Adams", role: "Data Engineer", company: "Data Company", status: "simulated", skills: ["Data Pipelines", "Spark", "Airflow"] },
  { id: "38", name: "Christopher Baker", role: "DevOps Lead", company: "Tech Corp", status: "simulated", skills: ["Kubernetes", "AWS", "CI/CD"] },
  { id: "39", name: "Lauren King", role: "Product Designer", company: "Design Studio", status: "simulated", skills: ["UI Design", "User Research", "Prototyping"] },
  { id: "40", name: "Andrew Scott", role: "Backend Engineer", company: "Startup", status: "simulated", skills: ["Go", "PostgreSQL", "APIs"] },
  { id: "41", name: "Nicole Young", role: "Frontend Lead", company: "Consumer Tech", status: "simulated", skills: ["React", "TypeScript", "Design Systems"] },
  { id: "42", name: "Joshua Hernandez", role: "ML Engineer", company: "AI Startup", status: "simulated", skills: ["TensorFlow", "Python", "MLOps"] },
  { id: "43", name: "Michelle Hill", role: "Head of Product", company: "Series A", status: "simulated", skills: ["Product Strategy", "Roadmap", "Analytics"] },
  { id: "44", name: "Brandon Martinez", role: "Engineering Manager", company: "Scale-up", status: "simulated", skills: ["Team Building", "Process", "Mentorship"] },
  { id: "45", name: "Stephanie Lopez", role: "UX Designer", company: "Agency", status: "simulated", skills: ["User Research", "Prototyping", "Testing"] },
  { id: "46", name: "Justin Gonzalez", role: "Full Stack Engineer", company: "Startup", status: "simulated", skills: ["React", "Node.js", "PostgreSQL"] },
  { id: "47", name: "Rachel Mitchell", role: "Data Scientist", company: "Analytics Co", status: "simulated", skills: ["Python", "SQL", "Statistics"] },
  { id: "48", name: "Tyler Perez", role: "Infrastructure Engineer", company: "Tech Company", status: "simulated", skills: ["AWS", "Terraform", "Monitoring"] },
  { id: "49", name: "Amanda Roberts", role: "Product Manager", company: "Enterprise", status: "simulated", skills: ["Enterprise Product", "B2B", "Strategy"] },
  { id: "50", name: "Jonathan Turner", role: "CTO", company: "Startup", status: "simulated", skills: ["Technical Leadership", "Architecture", "Hiring"] },

  // Unexplored profiles (not yet processed)
  { id: "51", name: "Rachel Liu", role: "Staff Eng", company: "FAANG", status: "unexplored", skills: ["ML", "Python", "Infrastructure"] },
  { id: "52", name: "James Taylor", role: "Backend Eng", company: "Startup", status: "unexplored", skills: ["Rust", "PostgreSQL", "APIs"] },
  { id: "53", name: "Mike Johnson", role: "DevOps Lead", company: "Tech Corp", status: "unexplored", skills: ["AWS", "Terraform", "CI/CD"] },
  { id: "54", name: "Nina Patel", role: "Product Designer", company: "Agency", status: "unexplored", skills: ["UI Design", "User Research", "Prototyping"] },
  { id: "55", name: "Ryan Lee", role: "Data Scientist", company: "Analytics Co", status: "unexplored", skills: ["Python", "SQL", "Statistics"] },
  { id: "56", name: "Maya Johnson", role: "Engineering Manager", company: "Scale-up", status: "unexplored", skills: ["Team Building", "Agile", "Mentorship"] },
  { id: "57", name: "Kevin Chen", role: "Frontend Engineer", company: "Consumer App", status: "unexplored", skills: ["React", "TypeScript", "CSS"] },
  { id: "58", name: "Lisa Anderson", role: "Product Manager", company: "SaaS", status: "unexplored", skills: ["Product", "Analytics", "Strategy"] },
  { id: "59", name: "David Park", role: "Backend Engineer", company: "Startup", status: "unexplored", skills: ["Go", "Microservices", "APIs"] },
  { id: "60", name: "Sarah Kim", role: "UX Designer", company: "Design Studio", status: "unexplored", skills: ["User Research", "Prototyping", "Testing"] },
  { id: "61", name: "Michael Chang", role: "ML Engineer", company: "AI Company", status: "unexplored", skills: ["PyTorch", "NLP", "MLOps"] },
  { id: "62", name: "Emily Wong", role: "Engineering Manager", company: "Tech Corp", status: "unexplored", skills: ["Team Leadership", "Process", "Hiring"] },
  { id: "63", name: "Daniel Zhang", role: "DevOps Engineer", company: "Scale-up", status: "unexplored", skills: ["Kubernetes", "AWS", "Monitoring"] },
  { id: "64", name: "Olivia Liu", role: "Product Designer", company: "Consumer Tech", status: "unexplored", skills: ["UI/UX", "Design Systems", "Research"] },
  { id: "65", name: "Ryan Patel", role: "Data Engineer", company: "Data Company", status: "unexplored", skills: ["Spark", "Airflow", "Data Pipelines"] },
  { id: "66", name: "Sophia Martinez", role: "Frontend Lead", company: "Startup", status: "unexplored", skills: ["React", "Vue", "Design Systems"] },
  { id: "67", name: "Alexander Brown", role: "Backend Lead", company: "Enterprise", status: "unexplored", skills: ["Java", "Spring", "Microservices"] },
  { id: "68", name: "Ava Davis", role: "Product Manager", company: "Series A", status: "unexplored", skills: ["Product Strategy", "Growth", "Analytics"] },
  { id: "69", name: "Noah Wilson", role: "Full Stack Engineer", company: "Startup", status: "unexplored", skills: ["Node.js", "React", "PostgreSQL"] },
  { id: "70", name: "Isabella Moore", role: "Design Lead", company: "Design Agency", status: "unexplored", skills: ["Design Strategy", "Research", "Prototyping"] },
  { id: "71", name: "Liam Taylor", role: "ML Engineer", company: "AI Lab", status: "unexplored", skills: ["TensorFlow", "Python", "Computer Vision"] },
  { id: "72", name: "Mia Garcia", role: "Engineering Manager", company: "Scale-up", status: "unexplored", skills: ["Team Building", "Agile", "Culture"] },
  { id: "73", name: "Ethan Rodriguez", role: "DevOps Lead", company: "Tech Company", status: "unexplored", skills: ["AWS", "Terraform", "CI/CD"] },
  { id: "74", name: "Charlotte Lee", role: "Product Designer", company: "Consumer App", status: "unexplored", skills: ["UX Design", "User Research", "Testing"] },
  { id: "75", name: "Alexander White", role: "Backend Engineer", company: "Startup", status: "unexplored", skills: ["Go", "PostgreSQL", "APIs"] },
  { id: "76", name: "Amelia Harris", role: "Data Scientist", company: "Analytics Co", status: "unexplored", skills: ["Python", "SQL", "Machine Learning"] },
  { id: "77", name: "Benjamin Clark", role: "Frontend Engineer", company: "Consumer Tech", status: "unexplored", skills: ["React", "TypeScript", "CSS"] },
  { id: "78", name: "Harper Lewis", role: "Product Manager", company: "SaaS", status: "unexplored", skills: ["Product", "Analytics", "GTM"] },
  { id: "79", name: "Mason Walker", role: "ML Engineer", company: "AI Startup", status: "unexplored", skills: ["PyTorch", "NLP", "MLOps"] },
  { id: "80", name: "Evelyn Hall", role: "Engineering Manager", company: "Tech Corp", status: "unexplored", skills: ["Team Leadership", "Process", "Mentorship"] },
  { id: "81", name: "Logan Allen", role: "DevOps Engineer", company: "Scale-up", status: "unexplored", skills: ["Kubernetes", "AWS", "Monitoring"] },
  { id: "82", name: "Abigail Young", role: "Design Lead", company: "Design Studio", status: "unexplored", skills: ["UI/UX", "Design Systems", "Research"] },
  { id: "83", name: "Lucas King", role: "Backend Lead", company: "Enterprise", status: "unexplored", skills: ["Java", "Microservices", "Architecture"] },
  { id: "84", name: "Elizabeth Wright", role: "Product Manager", company: "Series B", status: "unexplored", skills: ["Product Strategy", "Enterprise", "Analytics"] },
  { id: "85", name: "Henry Lopez", role: "Full Stack Engineer", company: "Startup", status: "unexplored", skills: ["Node.js", "React", "MongoDB"] },
  { id: "86", name: "Sofia Green", role: "UX Designer", company: "Agency", status: "unexplored", skills: ["User Research", "Prototyping", "Testing"] },
  { id: "87", name: "Jack Adams", role: "ML Engineer", company: "AI Company", status: "unexplored", skills: ["TensorFlow", "Python", "Deep Learning"] },
  { id: "88", name: "Victoria Baker", role: "Engineering Manager", company: "Scale-up", status: "unexplored", skills: ["Team Building", "Agile", "Hiring"] },
  { id: "89", name: "Owen Scott", role: "DevOps Lead", company: "Tech Corp", status: "unexplored", skills: ["AWS", "Docker", "CI/CD"] },
  { id: "90", name: "Grace Hill", role: "Product Designer", company: "Consumer Tech", status: "unexplored", skills: ["UI Design", "Design Systems", "Research"] },
  { id: "91", name: "Carter Mitchell", role: "Backend Engineer", company: "Startup", status: "unexplored", skills: ["Go", "PostgreSQL", "GraphQL"] },
  { id: "92", name: "Chloe Perez", role: "Data Engineer", company: "Data Company", status: "unexplored", skills: ["Spark", "Airflow", "Big Data"] },
  { id: "93", name: "Wyatt Roberts", role: "Frontend Lead", company: "Consumer App", status: "unexplored", skills: ["React", "TypeScript", "Performance"] },
  { id: "94", name: "Zoe Turner", role: "Product Manager", company: "SaaS", status: "unexplored", skills: ["Product", "Growth", "Analytics"] },
  { id: "95", name: "Nathan Phillips", role: "ML Engineer", company: "AI Lab", status: "unexplored", skills: ["PyTorch", "Computer Vision", "MLOps"] },
  { id: "96", name: "Lily Campbell", role: "Engineering Manager", company: "Tech Company", status: "unexplored", skills: ["Team Leadership", "Process", "Culture"] },
  { id: "97", name: "Sebastian Parker", role: "DevOps Engineer", company: "Scale-up", status: "unexplored", skills: ["Kubernetes", "GCP", "Monitoring"] },
  { id: "98", name: "Natalie Evans", role: "Design Lead", company: "Design Agency", status: "unexplored", skills: ["Design Strategy", "Research", "Prototyping"] },
  { id: "99", name: "Aiden Edwards", role: "Backend Engineer", company: "Startup", status: "unexplored", skills: ["Python", "Django", "APIs"] },
  { id: "100", name: "Hannah Collins", role: "Product Manager", company: "Series A", status: "unexplored", skills: ["Product Strategy", "User Research", "Analytics"] },
]
